name = "portfolio"
compatibility_date = "2024-01-01"
# pages_build_output_dir = "dist"

[vars]
ADMIN_PASSWORD = "4439"

[[r2_buckets]]
binding = "PORTFOLIO_BUCKET"
bucket_name = "pandadesign"
preview_bucket_name = "pandadesign-preview"
